version: '2'

services:
  app:
    entrypoint: [bin/start]
    image: bigbluebutton/greenlight:v2
    container_name: greenlight-v2
    env_file: .env
    restart: always
    ports:
      - 127.0.0.1:5000:80
    volumes:
      - ./log:/usr/src/app/log
    links:
      - db
  db:
    image: postgres:9.5
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./db/production:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
